#!/bin/bash
chmod +x /interface_setup
/interface_setup
rm /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
ip rou del default 2> /dev/null
ip route add default via 10.161.0.254 dev net0
echo "include \"/etc/bind/named.conf.zones\";" >> /etc/bind/named.conf.local
chown -R bind:bind /etc/bind/zones
service named start
chmod +x /enable_dnssec
/enable_dnssec

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
tail -f /dev/null

