# seedemu/core/ExternalEmulation.py
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Union

@dataclass(frozen=True)
class ExternalNetRef:
    """
    Reference a SEED network that the external emulator should attach to.
    - scope: "ix" or "as"
    - name:  e.g., "ix100" or "net0"
    - asn:   required only if scope="as"
    - ipv4:  optional fixed IP inside that docker network
    """
    scope: str               # "ix" | "as"
    name: str                # "ix100" | "net0" ...
    asn: Optional[int] = None
    ipv4: Optional[str] = None

@dataclass(frozen=True)
class ExternalFileSpec:
    """
    File to be generated by SEED into output/external_emulations/<name>/...
    """
    relpath: str             # e.g. "bmv2/s1.json" or "startup.sh"
    content: Union[str, bytes]

@dataclass
class ExternalEmuSpec:
    """
    A target integration definition (Task 3):
    - what files to generate
    - what service/container to start
    - what SEED networks to attach to
    """
    name: str
    image: str
    command: Union[str, List[str]] = ""
    workdir: Optional[str] = None
    env: Dict[str, str] = field(default_factory=dict)

    # Files generated by SEED into output bundle
    files: List[ExternalFileSpec] = field(default_factory=list)

    # Attach to SEED networks
    networks: List[ExternalNetRef] = field(default_factory=list)

    # Bind-mount generated folder into container at this path
    mount_to: str = "/seedext"

    # Some emulators need privileges/caps
    privileged: bool = True
    cap_add_all: bool = True