#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.153.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-44-15.792892000Z--51dd5f54c9c416dc7c2bd5ebcc0cf2b5061bbb3e /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-44-17.327348000Z--11bb6c9f0876fbb5efe7d07ca357ea48bd8023ca /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0x51DD5f54C9C416Dc7C2bd5eBCC0cF2B5061bBb3E" --mine --miner.threads=1 --unlock "0x51DD5f54C9C416Dc7C2bd5eBCC0cF2B5061bBb3E, 0x11BB6c9f0876Fbb5EFe7d07Ca357EA48bD8023ca" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

