version: "3"

services:
    seedemu-client:
        build: .
        container_name: seedemu_client
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        cap_add:
            - ALL
        privileged: true