#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.170.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-43-51.505501000Z--209516955e14b218dcd10fc11a77d38bcae29cda /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-43-53.420281000Z--3c3d62795e9315655ae10cc0043c36a0b37326d1 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0x209516955E14B218dCd10Fc11A77d38bcAe29CdA" --mine --miner.threads=1 --unlock "0x209516955E14B218dCd10Fc11A77d38bcAe29CdA, 0x3C3D62795e9315655aE10CC0043C36A0B37326d1" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

