#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.151.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-43-57.436841000Z--3c5db19ddd7198ba32becc61eeda30314c28a252 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-43-59.332630000Z--2965c734dc0df357e0fe65f48fb45f3a243fade5 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0x3C5DB19dDd7198Ba32beCC61eeda30314C28a252" --mine --miner.threads=1 --unlock "0x3C5DB19dDd7198Ba32beCC61eeda30314C28a252, 0x2965c734dC0DF357E0fe65F48FB45F3A243faDe5" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

