version: "3"

services:
    seedemu-demo-system:
        build:
            context: .
            args:
                http_proxy: http://10.1.10.61:7890
                https_proxy: http://10.1.10.61:7890
                HTTP_PROXY: http://10.1.10.61:7890
                HTTPS_PROXY: http://10.1.10.61:7890
        image: handsonsecurity/seedemu-demosystem:2.0
        container_name: seedemu_demo_system
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/BaseDir
        ports:
            - 5050:5050
        cap_add:
            - ALL
        privileged: true
        environment:
            - HOST=192.168.254.131
