version: "3"

services:
    seedemu-demo-system:
        build:
            context: .
        image: handsonsecurity/seedemu-demosystem:2.0
        container_name: seedemu_demo_system
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/DemoSystem
        ports:
            - 5050:5050
        cap_add:
            - ALL
        pid: host
        privileged: true
