#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.150.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-44-18.755502000Z--fa9a6efe9c6b694565c41ab59f3fb248222ad564 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-44-20.188086000Z--7d9a717fd368a0ea4d194a9bc0b0cda553ab0994 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0xfA9a6EFe9C6b694565C41aB59F3FB248222ad564" --mine --miner.threads=1 --unlock "0xfA9a6EFe9C6b694565C41aB59F3FB248222ad564, 0x7d9A717FD368A0EA4D194a9bC0B0CdA553aB0994" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

