#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.162.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-44-07.065720000Z--6f564eb6ac6e59b35e142fa1bbecaacbd6cd1e27 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-44-09.269682000Z--e6f4700830f6a40462d042784bd854e718cb2096 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0x6f564Eb6AC6E59b35E142fA1BBEcaaCbd6CD1E27" --mine --miner.threads=1 --unlock "0x6f564Eb6AC6E59b35E142fA1BBEcaaCbd6CD1E27, 0xe6f4700830F6A40462d042784Bd854E718Cb2096" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

