#!/bin/bash
chmod +x /interface_setup
/interface_setup
chmod +x /ovpn_startup
/ovpn_startup net0
ip route add default via 192.168.160.1 dev 000_svc
ip li add dummy0 type dummy
ip li set dummy0 up
ip addr add 10.0.0.19/32 dev dummy0
[ ! -d /run/bird ] && mkdir /run/bird
bird -d &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

