#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.163.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-44-23.155541000Z--d3ea8d4887790ca3c5c321e256a1a6bf27daf6f0 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-44-24.482583000Z--f3d046b49c7b359a0dd0ad803534cf086182c12b /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0xd3eA8d4887790ca3c5C321e256A1a6Bf27DAF6f0" --mine --miner.threads=1 --unlock "0xd3eA8d4887790ca3c5C321e256A1a6Bf27DAF6f0, 0xF3D046b49C7B359a0dD0aD803534cf086182c12B" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

