#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.154.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-43-47.666361000Z--a1cd262e156147fca285f0ad0aa7e2901b96b7f2 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-43-49.620288000Z--fa35ff9923227a2058fa99bda327d73b1fa984f9 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0xA1cd262e156147Fca285f0Ad0aa7e2901B96B7F2" --mine --miner.threads=1 --unlock "0xA1cd262e156147Fca285f0Ad0aa7e2901B96B7F2, 0xfA35Ff9923227A2058Fa99bda327d73b1Fa984F9" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

