#!/bin/bash
chmod +x /interface_setup
/interface_setup
rm /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
ip rou del default 2> /dev/null
ip route add default via 10.154.0.254 dev net0

printf "%s" "waiting for C2 Server network ready ..."
while ! ping -c 1 -n -w 1 10.150.0.71 &> /dev/null
do
    printf "%c" "."
done
printf "\n%s\n"  "Server is ready"
sleep 3
python3 /tmp/BotClient.py


echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
tail -f /dev/null

