#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.152.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-06-16T05-44-11.060146000Z--98263bf40091903b3701f9fb061fa21c32067b6f /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2022-06-16T05-44-12.551825000Z--c49ba63b24f05d8b8e85a2946cf5634a9c157f09 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --miner.etherbase "0x98263BF40091903B3701F9fb061fA21c32067B6f" --mine --miner.threads=1 --unlock "0x98263BF40091903B3701F9fb061fA21c32067B6f, 0xc49ba63B24F05d8b8e85a2946CF5634A9C157f09" --password "/tmp/eth-password" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique --bootnodes "$(cat /tmp/eth-node-urls)"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

