#!/bin/bash
chmod +x /ovpn_startup
/ovpn_startup net0
chmod +x /interface_setup
/interface_setup
rm /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
ip rou del default 2> /dev/null
ip route add default via 10.171.0.254 dev net0

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
tail -f /dev/null

