#!/usr/bin/env python3
"""Python entrypoint for destroyKvmVms with its shell body embedded."""
from __future__ import annotations

import sys
from pathlib import Path

from _embeddedShell import runEmbeddedShell


SHELL_BODY = r'''#!/usr/bin/env bash
# Destroy KVM VMs recorded in kvmState.yaml.
# Inputs: kvmState.yaml generated by createKvmVms.py.
# Outputs/side effects: destroys matching libvirt domains, removes DHCP
# reservations/leases, disks, cloud-init files, generated kubeconfig/inventory,
# and then verifies the cleanup. The disk-dir guard prevents deleting unrelated
# VMs whose names happen to match.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${SEED_K8S_ENTRYPOINT}")" && pwd)"
SETUP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_PATH="${1:-${SETUP_DIR}/kvmState.yaml}"
HELPER="${SCRIPT_DIR}/manageKvmConfig.py"
NODES_TSV=""
VERIFY_NODES_TSV=""
dnsmasqStatus="/var/lib/libvirt/dnsmasq/virbr0.status"
setupOutputGlob="${SETUP_DIR}/seedemu-k3s.*"

usage() {
    cat <<EOF
Usage: $0 [kvmState.yaml]

Clean KVM guests recorded in kvmState.yaml and verify that no domain, DHCP
reservation, DHCP lease, disk, cloud-init directory, or generated setup output
remains.
EOF
}

requireCommand() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Missing required command: $1" >&2
        exit 1
    }
}

cleanupTmp() {
    [ -n "${NODES_TSV}" ] && rm -f "${NODES_TSV}" || true
    [ -n "${VERIFY_NODES_TSV}" ] && rm -f "${VERIFY_NODES_TSV}" || true
}

loadConfig() {
    if [ ! -s "${CONFIG_PATH}" ]; then
        echo "KVM state not found or empty: ${CONFIG_PATH}" >&2
        echo "Run createKvmVms.py first so it generates kvmState.yaml." >&2
        exit 1
    fi
    eval "$(python3 "${HELPER}" "${SETUP_DIR}/kvm.yaml" state-vars --state "${CONFIG_PATH}")"
    kvmBridgeName="$(virsh net-dumpxml "${kvmNetwork}" 2>/dev/null | python3 -c 'import sys, xml.etree.ElementTree as ET; data=sys.stdin.read(); print((ET.fromstring(data).find(".//bridge").get("name") if data.strip() else "") or "")' 2>/dev/null || true)"
    if [ -n "${kvmBridgeName}" ]; then
        dnsmasqStatus="/var/lib/libvirt/dnsmasq/${kvmBridgeName}.status"
    else
        dnsmasqStatus="/var/lib/libvirt/dnsmasq/${kvmNetwork}.status"
    fi
    NODES_TSV="$(mktemp "${SCRIPT_DIR}/destroy-nodes.XXXXXX.tsv")"
    VERIFY_NODES_TSV="$(mktemp "${SCRIPT_DIR}/destroy-verify-nodes.XXXXXX.tsv")"
    python3 "${HELPER}" "${SETUP_DIR}/kvm.yaml" state-nodes-tsv --state "${CONFIG_PATH}" > "${NODES_TSV}"
    cp "${NODES_TSV}" "${VERIFY_NODES_TSV}"
}

printPlan() {
    echo "Cleaning KVM nodes from: ${CONFIG_PATH}"
    echo "KVM network: ${kvmNetwork}"
    echo "Disk dir: ${kvmDiskDir}"
    echo "Cloud-init dir: ${kvmCloudInitDir}"
    awk -F '\t' '{printf "  %-24s role=%-6s ip=%-15s mac=%s\n", $1, $2, $3, $4}' "${NODES_TSV}"
}

cleanupDomainsReservationsAndFiles() {
    while IFS=$'\t' read -r name role ip mac vcpus memory_mb disk_gb; do
        [ -n "${name}" ] || continue
        echo "Cleaning VM ${name} (${ip}, ${mac})"

        if virsh dominfo "${name}" >/dev/null 2>&1; then
            validateDestroyTargetBelongsToSetup "${name}"
            virsh destroy "${name}" >/dev/null 2>&1 || true
            virsh undefine "${name}" --nvram --remove-all-storage >/dev/null 2>&1 \
                || virsh undefine "${name}" --nvram >/dev/null 2>&1 \
                || virsh undefine "${name}" >/dev/null
        fi

        if [ -n "${ip}" ] && [ -n "${mac}" ]; then
            local host_xml="<host mac='${mac}' name='${name}' ip='${ip}'/>"
            virsh net-update "${kvmNetwork}" delete ip-dhcp-host "${host_xml}" --live --config >/dev/null 2>&1 || true
        fi

        rm -rf "${kvmCloudInitDir}/${name}"
        rm -f "${kvmDiskDir}/${name}.qcow2"
    done < "${NODES_TSV}"
}

validateDestroyTargetBelongsToSetup() {
    # Args:
    #   $1: VM domain name to validate before destructive cleanup.
    # Uses kvmDiskDir from kvmState.yaml. This prevents a stale state file from
    # deleting a pre-existing cluster VM whose disk lives elsewhere.
    local vm_name="$1"
    local disk_path=""
    disk_path="$(
        virsh domblklist "${vm_name}" --details 2>/dev/null \
        | awk '$2 == "disk" && $4 != "-" && path == "" {path=$4} END {print path}'
    )"
    if [ -z "${disk_path}" ]; then
        echo "Cannot determine disk path for ${vm_name}; refusing destructive cleanup." >&2
        exit 1
    fi
    case "${disk_path}" in
        "${kvmDiskDir}"/*) ;;
        *)
            echo "Refusing to destroy ${vm_name}: disk is outside this setup disk dir." >&2
            echo "  vm_disk=${disk_path}" >&2
            echo "  setup_disk_dir=${kvmDiskDir}" >&2
            echo "This usually means kvmState.yaml is stale or points to an existing cluster." >&2
            exit 1
            ;;
    esac
}

cleanupDnsmasqStaleLeases() {
    [ -f "${dnsmasqStatus}" ] || return 0

    local tmp_nodes
    tmp_nodes="$(mktemp)"
    awk -F '\t' 'NF >= 4 {print $1 "\t" $3 "\t" tolower($4)}' "${NODES_TSV}" > "${tmp_nodes}"

    sudo cp "${dnsmasqStatus}" "${dnsmasqStatus}.bak.$(date +%Y%m%d_%H%M%S)"
    sudo python3 - "${dnsmasqStatus}" "${tmp_nodes}" <<'PY'
import json
import sys
from pathlib import Path

status_path = Path(sys.argv[1])
nodes_path = Path(sys.argv[2])

remove_names = set()
remove_ips = set()
remove_macs = set()
for line in nodes_path.read_text(encoding="utf-8").splitlines():
    parts = line.split("\t")
    if len(parts) < 3:
        continue
    name, ip, mac = parts[:3]
    if name:
        remove_names.add(name)
    if ip:
        remove_ips.add(ip)
    if mac:
        remove_macs.add(mac.lower())

try:
    data = json.loads(status_path.read_text(encoding="utf-8") or "[]")
except json.JSONDecodeError:
    raise SystemExit(f"Invalid dnsmasq status JSON: {status_path}")

filtered = [
    item for item in data
    if not (
        item.get("hostname") in remove_names
        or item.get("ip-address") in remove_ips
        or str(item.get("mac-address", "")).lower() in remove_macs
    )
]
status_path.write_text(json.dumps(filtered, indent=2) + "\n", encoding="utf-8")
PY
    rm -f "${tmp_nodes}"
}

cleanupSetupOutputs() {
    echo "Cleaning stale setup outputs matching: ${setupOutputGlob}"
    rm -f ${setupOutputGlob}
    rm -f "${CONFIG_PATH}" "${outputK3sConfig}" "${outputKubeconfig}" "${outputInventory}"
    rm -f "${SETUP_DIR}/configRunning.yaml"
}

verifyClean() {
    local failed=0

    echo "Verifying cleanup..."

    while IFS=$'\t' read -r name role ip mac vcpus memory_mb disk_gb; do
        [ -n "${name}" ] || continue
        if virsh dominfo "${name}" >/dev/null 2>&1; then
            echo "Residual domain: ${name}" >&2
            failed=1
        fi
        if [ -e "${kvmDiskDir}/${name}.qcow2" ]; then
            echo "Residual disk: ${kvmDiskDir}/${name}.qcow2" >&2
            failed=1
        fi
        if [ -e "${kvmCloudInitDir}/${name}" ]; then
            echo "Residual cloud-init dir: ${kvmCloudInitDir}/${name}" >&2
            failed=1
        fi

        if virsh net-dumpxml "${kvmNetwork}" 2>/dev/null \
            | grep -E "<host[[:space:]][^>]*(mac=['\"]${mac}['\"]|name=['\"]${name}['\"]|ip=['\"]${ip}['\"])" >/dev/null 2>&1; then
            echo "Residual DHCP reservation in libvirt network ${kvmNetwork}: ${name} ${ip} ${mac}" >&2
            failed=1
        fi

        if virsh net-dhcp-leases "${kvmNetwork}" 2>/dev/null \
            | awk -v name="${name}" -v ip="${ip}/24" -v mac="$(printf '%s' "${mac}" | tr '[:upper:]' '[:lower:]')" '
                NR > 2 {
                    row = tolower($0)
                    if (row ~ mac && $5 == ip && $6 == name) {
                        found = 1
                    }
                }
                END { exit(found ? 0 : 1) }
            '; then
            echo "Residual DHCP lease in libvirt network ${kvmNetwork}: ${name} ${ip} ${mac}" >&2
            failed=1
        fi
    done < "${VERIFY_NODES_TSV}"

    if [ -e "${CONFIG_PATH}" ]; then
        echo "Residual KVM state: ${CONFIG_PATH}" >&2
        failed=1
    fi

    if compgen -G "${setupOutputGlob}" >/dev/null; then
        echo "Residual setup output files matching ${setupOutputGlob}" >&2
        compgen -G "${setupOutputGlob}" >&2 || true
        failed=1
    fi

    if [ "${failed}" -ne 0 ]; then
        echo "Cleanup verification failed." >&2
        exit 1
    fi
    echo "Cleanup verification passed."
}

main() {
    if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
        usage
        exit 0
    fi

    requireCommand awk
    requireCommand grep
    requireCommand mktemp
    requireCommand python3
    requireCommand sudo
    requireCommand virsh

    trap cleanupTmp EXIT
    loadConfig
    printPlan
    cleanupDomainsReservationsAndFiles
    cleanupDnsmasqStaleLeases
    cleanupSetupOutputs
    verifyClean
}

main "$@"
'''


def main(argv: list[str] | None = None) -> int:
    """Run this entrypoint with optional argv override for tests."""
    return runEmbeddedShell(Path(__file__), list(sys.argv[1:] if argv is None else argv), SHELL_BODY)


if __name__ == "__main__":
    raise SystemExit(main())
