#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.150.0.254 dev net0
cat /tmp/etc-hosts >> /etc/hosts

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
python3.7 /webserver.py --w_ip=${WS_IP} --w_port=${WS_PORT} > carla_webserver.logs 2>&1
tail -f /dev/null

