#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.152.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-07-12T22-28-33.878711000Z--2138e32d758affcd89c7b2639ffd0a3cbe0f2956 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
nice -n 19 geth --datadir /root/.ethereum --identity="NODE_5" --networkid=10 --syncmode full --verbosity=2 --allow-insecure-unlock --port 30303 --bootnodes "$(cat /tmp/eth-node-urls)" --unlock "0x2138e32D758AfFCD89C7B2639Ffd0a3cbE0F2956" --password "/tmp/eth-password" --miner.etherbase "" --mine --miner.threads=1  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

