#!/bin/bash
[ ! -d /dev/net ] && mkdir /dev/net
mknod /dev/net/tun c 10 200
openvpn --config /ovpn-server.conf &
while ! ip li sh tap0; do sleep 1; done
ip li set tap0 up
addr="`ip -br ad sh eth0 | awk '{ print $3 }'`"
gw="`ip rou sh default | cut -d' ' -f3`"
ip addr fl eth0
brctl addbr br0
brctl addif br0 eth0
brctl addif br0 tap0
ip addr add "$addr" dev br0
ip li set br0 up
ip rou add default via "$gw" dev br0

