from __future__ import annotations

import json
import os
import ipaddress
import re
import shutil
from hashlib import md5, sha1
from os import chdir, mkdir
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import yaml

from seedemu.compiler.Docker import Docker
from seedemu.core import Network, Node


INTERNET_MAP_META_PREFIX = "org.seedsecuritylabs.seedemu.meta."
# Border routers are already represented through the router node path in SEED's
# registry. Compiling "brdnode" again creates duplicate Deployment names.
SEEDEMU_NODE_TYPES = ["rnode", "csnode", "hnode", "rs", "snode"]


class SchedulingStrategy:
    """Compatibility constants for older Kubernetes compiler callers."""

    NONE = "none"
    AUTO = "auto"
    BY_AS = "by_as"
    BY_AS_HARD = "by_as_hard"
    BY_ROLE = "by_role"
    CUSTOM = "custom"


class KubernetesCompiler(Docker):
    """Minimal Kubernetes compiler for a k8s-native baseline.

    Design goals:
    - public compiler name is KubernetesCompiler
    - macvlan+VLAN is the default secondary CNI; kube-ovn remains available
    - no inventory dependency during compile
    - no nodeSelector / affinity / topology spreading
    - no node-aware preload planning
    - generated orchestration artifacts are limited to one manifest file and
      images.yaml; build/deploy orchestration lives in seedemu.k8sTools.
    """

    __namespace: str
    __cni_type: str
    __local_link_cni_type: str | None
    __cni_master_interface: str
    __cni_mtu: int | None
    __macvlan_vlan_mode: bool
    __macvlan_vlan_id_start: int
    __macvlan_vlan_trunks: List[Dict[str, Any]]
    __macvlan_vlan_allocations: Dict[str, Tuple[str, str, int]]
    __image_pull_policy: str
    __image_registry_prefix: str
    __manifests: List[Dict[str, Any]]
    __image_entries: List[Dict[str, str]]

    def __init__(
        self,
        image_registry_prefix: str = "seedemu",
        registry_prefix: str | None = None,
        namespace: str = "seedemu",
        use_multus: bool = True,
        cni_type: str = "macvlan",
        local_link_cni_type: str | None = None,
        cni_master_interface: str = "ens2",
        cni_mtu: int | None = None,
        macvlan_vlan_mode: bool = True,
        macvlan_vlan_id_start: int = 100,
        macvlan_vlan_trunks: Optional[List[Dict[str, Any]]] = None,
        image_pull_policy: str = "Always",
        scheduling_strategy: str = SchedulingStrategy.NONE,
        node_labels: Dict[str, Dict[str, str]] | None = None,
        default_resources: Dict[str, Dict[str, str]] | None = None,
        generate_services: bool = False,
        service_type: str = "ClusterIP",
        **kwargs: Any,
    ) -> None:
        kwargs["selfManagedNetwork"] = True
        super().__init__(**kwargs)
        if not use_multus:
            raise ValueError("KubernetesCompiler requires Multus network attachments.")
        if registry_prefix is not None:
            image_registry_prefix = registry_prefix
        self.__image_registry_prefix = image_registry_prefix.strip().strip("/")
        self.__namespace = namespace.strip() or "seedemu"
        self.__cni_type = self._normalizeCniType(cni_type)
        if local_link_cni_type is not None and str(local_link_cni_type).strip():
            self.__local_link_cni_type = self._normalizeCniType(str(local_link_cni_type))
        else:
            self.__local_link_cni_type = None
        self.__cni_master_interface = cni_master_interface.strip() or "eth0"
        self.__cni_mtu = int(cni_mtu) if cni_mtu is not None else None
        if self.__cni_mtu is not None and not 576 <= self.__cni_mtu <= 65535:
            raise ValueError("cni_mtu must be in range 576..65535")
        self.__macvlan_vlan_mode = bool(macvlan_vlan_mode)
        self.__macvlan_vlan_id_start = int(macvlan_vlan_id_start)
        if not 1 <= self.__macvlan_vlan_id_start <= 4094:
            raise ValueError("macvlan_vlan_id_start must be in VLAN range 1..4094")
        self.__macvlan_vlan_trunks = self._normalizeMacvlanVlanTrunks(macvlan_vlan_trunks)
        self.__macvlan_vlan_allocations = {}
        self.__image_pull_policy = image_pull_policy.strip() or "Always"
        self.__manifests = []
        self.__image_entries = []

    def getName(self) -> str:
        return "Kubernetes"

    def getManifestName(self) -> str:
        """Return the manifest filename generated by this compiler."""
        if self._usesKubeOvn():
            return "k8s.kube-ovn.yaml"
        return "k8s.yaml"

    @staticmethod
    def _normalizeCniType(cni_type: str | None) -> str:
        """Normalize and validate the secondary CNI mode."""
        value = (cni_type or "macvlan").strip().lower().replace("_", "-")
        if value in {"kube-ovn", "ovn"}:
            return "kube-ovn"
        if value == "macvlan":
            return "macvlan"
        raise ValueError(
            f"KubernetesCompiler supports only cni_type \"kube-ovn\" or "
            f"cni_type \"macvlan\"; got {cni_type!r}."
        )

    @staticmethod
    def _safeBridgeName(name: str) -> str:
        return f"br-{md5(name.encode()).hexdigest()[:12]}"

    def _usesKubeOvn(self) -> bool:
        """Return true when the compiler should emit Kube-OVN resources."""
        return self.__cni_type == "kube-ovn"

    def _doCompile(self, emulator) -> None:
        registry = emulator.getRegistry()
        self._groupSoftware(emulator)

        self.__manifests.append(
            {
                "apiVersion": "v1",
                "kind": "Namespace",
                "metadata": {"name": self.__namespace},
            }
        )

        for ((_, obj_type, _), obj) in registry.getAll().items():
            if obj_type == "net":
                self.__manifests.append(self._compileNetK8s(obj))

        for ((_, obj_type, _), obj) in registry.getAll().items():
            if obj_type in SEEDEMU_NODE_TYPES:
                self.__manifests.append(self._compileNodeK8s(obj))

        manifests = (
            self._renderKubeOvnManifests(self.__manifests)
            if self._usesKubeOvn()
            else self.__manifests
        )
        with open(self.getManifestName(), "w", encoding="utf-8") as handle:
            yaml.safe_dump_all(manifests, handle, sort_keys=False)

        self._writeNetworkingMetadata()
        self._stage_base_image_contexts()
        with open("images.yaml", "w", encoding="utf-8") as handle:
            yaml.safe_dump({"images": self.__image_entries}, handle, sort_keys=False)

    def _compileNetK8s(self, net: Network) -> Dict[str, Any]:
        name = self._getRealNetName(net).replace("_", "-").lower()

        if self._usesKubeOvn():
            config = {
                "cniVersion": "0.3.1",
                "type": "kube-ovn",
                "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
                "provider": f"{name}.{self.__namespace}.ovn",
            }
        elif self.__cni_type == "macvlan":
            master_interface = self.__cni_master_interface
            vlan_id = None
            vlan_base_interface = None
            vlan_trunk = None
            if self.__macvlan_vlan_mode:
                vlan_trunk, vlan_base_interface, vlan_id = self._macvlanVlanAllocation(name)
                master_interface = f"{vlan_base_interface}.{vlan_id}"
            config = {
                "cniVersion": "0.3.1",
                "type": "macvlan",
                "master": master_interface,
                "mode": "bridge",
                "ipam": {"type": "static"},
            }
            if self.__cni_mtu is not None:
                config["mtu"] = self.__cni_mtu
        else:
            raise ValueError(f"unsupported Kubernetes CNI type: {self.__cni_type}")

        annotations = self._getInternetMapNetMeta(net)
        if self.__cni_type == "macvlan" and vlan_id is not None:
            annotations[self._metaKey("vlan-id")] = str(vlan_id)
            annotations[self._metaKey("vlan-base-interface")] = str(vlan_base_interface)
            annotations[self._metaKey("vlan-master-interface")] = master_interface
            annotations[self._metaKey("vlan-trunk")] = str(vlan_trunk)

        return {
            "apiVersion": "k8s.cni.cncf.io/v1",
            "kind": "NetworkAttachmentDefinition",
            "metadata": {
                "name": name,
                "namespace": self.__namespace,
                "annotations": annotations,
            },
            "spec": {"config": json.dumps(config)},
        }

    def _normalizeMacvlanVlanTrunks(
        self,
        raw_trunks: Optional[List[Dict[str, Any]]],
    ) -> List[Dict[str, Any]]:
        """Normalize and validate VLAN ranges used by macvlan parents."""
        if not raw_trunks:
            raw_trunks = [
                {
                    "name": "trunk0",
                    "masterInterface": self.__cni_master_interface,
                    "vlanStart": self.__macvlan_vlan_id_start,
                    "vlanEnd": 4094,
                }
            ]

        trunks: List[Dict[str, Any]] = []
        seen_names: Set[str] = set()
        seen_interfaces: Set[str] = set()
        for index, item in enumerate(raw_trunks):
            if not isinstance(item, dict):
                raise ValueError(f"macvlan_vlan_trunks[{index}] must be a mapping")
            name = str(item.get("name") or f"trunk{index}").strip()
            master_interface = str(
                item.get("masterInterface") or item.get("master_interface") or ""
            ).strip()
            if not name:
                raise ValueError(f"macvlan_vlan_trunks[{index}] requires name")
            if not master_interface:
                raise ValueError(f"macvlan_vlan_trunks[{index}] requires masterInterface")
            if name in seen_names:
                raise ValueError(f"duplicate macvlan VLAN trunk name: {name}")
            if master_interface in seen_interfaces:
                raise ValueError(
                    f"duplicate macvlan VLAN trunk masterInterface: {master_interface}"
                )
            seen_names.add(name)
            seen_interfaces.add(master_interface)
            vlan_start = int(
                item.get("vlanStart")
                or item.get("vlan_start")
                or self.__macvlan_vlan_id_start
            )
            vlan_end = int(item.get("vlanEnd") or item.get("vlan_end") or 4094)
            if vlan_start < 1 or vlan_end > 4094 or vlan_start > vlan_end:
                raise ValueError(
                    f"invalid VLAN range for VLAN trunk {name}: "
                    f"{vlan_start}..{vlan_end}; expected 1..4094"
                )
            trunks.append(
                {
                    "name": name,
                    "masterInterface": master_interface,
                    "vlanStart": vlan_start,
                    "vlanEnd": vlan_end,
                }
            )
        return trunks

    def _macvlanVlanAllocation(self, network_name: str) -> Tuple[str, str, int]:
        """Return the configured trunk, base interface, and VLAN for a network."""
        if network_name not in self.__macvlan_vlan_allocations:
            remaining = len(self.__macvlan_vlan_allocations)
            total_capacity = 0
            for trunk in self.__macvlan_vlan_trunks:
                vlan_start = int(trunk["vlanStart"])
                vlan_end = int(trunk["vlanEnd"])
                capacity = vlan_end - vlan_start + 1
                total_capacity += capacity
                if remaining < capacity:
                    self.__macvlan_vlan_allocations[network_name] = (
                        str(trunk["name"]),
                        str(trunk["masterInterface"]),
                        vlan_start + remaining,
                    )
                    break
                remaining -= capacity
            else:
                raise ValueError(
                    "VLAN-backed macvlan mode ran out of VLAN IDs across configured "
                    f"trunks: capacity={total_capacity}"
                )
        return self.__macvlan_vlan_allocations[network_name]

    def _writeNetworkingMetadata(self) -> None:
        """Write compile-time network settings consumed by deployment wrappers."""
        with open("networking.yaml", "w", encoding="utf-8") as handle:
            yaml.safe_dump(
                {
                    "compiler": self.getName(),
                    "networkBackend": self.__cni_type,
                    "cniType": self.__cni_type,
                    "localLinkCniType": self.__local_link_cni_type or "",
                    "cniMasterInterface": self.__cni_master_interface,
                    "cniMtu": self.__cni_mtu,
                    "macvlanVlanMode": self.__macvlan_vlan_mode,
                    "macvlanVlanIdStart": self.__macvlan_vlan_id_start,
                    "macvlanVlanTrunks": (
                        self.__macvlan_vlan_trunks if self.__macvlan_vlan_mode else []
                    ),
                    "runtimeManifest": self.getManifestName(),
                },
                handle,
                sort_keys=False,
            )

    def _renderKubeOvnManifests(self, manifests: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Convert compiler manifests to Kube-OVN secondary-network resources.

        Args:
            manifests: Namespace, NAD, and workload manifests generated by the
                compiler before fabric-specific conversion.

        Returns:
            Manifest list containing a Kube-OVN Vpc, one Subnet per SeedEMU
            network, kube-ovn NADs, and workloads with provider IP annotations.
        """
        namespace_name = self._findManifestNamespace(manifests)
        vpc_name = self._kubeOvnResourceName("vpc", namespace_name)
        rendered: List[Dict[str, Any]] = []
        vpc_written = False

        for manifest in manifests:
            if manifest.get("kind") == "Namespace" and not vpc_written:
                rendered.append(manifest)
                rendered.append(self._kubeOvnVpc(namespace_name, vpc_name))
                vpc_written = True
                continue
            if manifest.get("kind") == "NetworkAttachmentDefinition":
                rendered.extend(self._convertNetworkAttachmentToKubeOvn(manifest, namespace_name, vpc_name))
                continue
            self._convertWorkloadAnnotationsToKubeOvn(manifest, namespace_name)
            rendered.append(manifest)

        if not vpc_written:
            rendered.insert(0, self._kubeOvnVpc(namespace_name, vpc_name))
        return rendered

    def _findManifestNamespace(self, manifests: List[Dict[str, Any]]) -> str:
        """Return the namespace used by workload manifests."""
        for manifest in manifests:
            if manifest.get("kind") == "Namespace":
                name = (manifest.get("metadata") or {}).get("name")
                if name:
                    return str(name)
        for manifest in manifests:
            metadata = manifest.get("metadata") or {}
            name = metadata.get("namespace")
            if name:
                return str(name)
        return self.__namespace

    def _kubeOvnResourceName(self, prefix: str, value: str) -> str:
        """Return a DNS-safe Kube-OVN cluster-scoped resource name."""
        safe = "".join(ch if ch.isalnum() or ch == "-" else "-" for ch in value.lower()).strip("-")
        digest = sha1(value.encode("utf-8")).hexdigest()[:8]
        return f"{prefix}-{digest}-{safe}"[:63].rstrip("-")

    def _kubeOvnVpc(self, namespace_name: str, vpc_name: str) -> Dict[str, Any]:
        """Return a Kube-OVN Vpc that isolates one SeedEMU namespace."""
        return {
            "apiVersion": "kubeovn.io/v1",
            "kind": "Vpc",
            "metadata": {"name": vpc_name},
            "spec": {"namespaces": [namespace_name]},
        }

    def _convertNetworkAttachmentToKubeOvn(
        self,
        manifest: Dict[str, Any],
        default_namespace: str,
        vpc_name: str,
    ) -> List[Dict[str, Any]]:
        """Return [Subnet, NAD] for one SeedEMU network."""
        metadata = manifest.get("metadata") or {}
        nad_name = str(metadata.get("name") or "")
        namespace_name = str(metadata.get("namespace") or default_namespace)
        if not nad_name:
            return [manifest]
        annotations = metadata.get("annotations") or {}
        prefix = annotations.get(self._metaKey("prefix"))
        if not prefix:
            raise ValueError(f"NAD {namespace_name}/{nad_name} lacks SeedEMU prefix annotation")

        provider = f"{nad_name}.{namespace_name}.ovn"
        subnet_name = self._kubeOvnResourceName("subnet", f"{namespace_name}-{nad_name}")
        subnet = {
            "apiVersion": "kubeovn.io/v1",
            "kind": "Subnet",
            "metadata": {"name": subnet_name},
            "spec": {
                "protocol": "IPv4",
                "provider": provider,
                "vpc": vpc_name,
                "cidrBlock": str(prefix),
                "gateway": self._firstUsableIp(str(prefix)),
                "gatewayType": "distributed",
                "natOutgoing": False,
                "private": False,
            },
        }

        converted = dict(manifest)
        converted["spec"] = {
            "config": json.dumps(
                {
                    "cniVersion": "0.3.1",
                    "type": "kube-ovn",
                    "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
                    "provider": provider,
                },
                separators=(",", ":"),
            )
        }
        return [subnet, converted]

    def _convertWorkloadAnnotationsToKubeOvn(
        self,
        manifest: Dict[str, Any],
        default_namespace: str,
    ) -> None:
        """Rewrite Multus static IP annotations for Kube-OVN attached NICs."""
        annotations = self._getPodTemplateAnnotations(manifest)
        if not annotations:
            return
        raw_networks = annotations.get("k8s.v1.cni.cncf.io/networks")
        if not isinstance(raw_networks, str):
            return
        try:
            networks = json.loads(raw_networks)
        except json.JSONDecodeError:
            return
        if not isinstance(networks, list):
            return

        changed = False
        for item in networks:
            if not isinstance(item, dict):
                continue
            ips = item.pop("ips", None)
            if not ips:
                continue
            nad_name, nad_namespace = self._parseNetworkSelection(item, default_namespace)
            if not nad_name:
                continue
            ip_values = [str(ip_value).strip().split("/", 1)[0] for ip_value in ips if str(ip_value).strip()]
            if not ip_values:
                continue
            annotations[f"{nad_name}.{nad_namespace}.ovn.kubernetes.io/ip_address"] = ",".join(ip_values)
            changed = True

        if changed:
            annotations["k8s.v1.cni.cncf.io/networks"] = json.dumps(networks, separators=(",", ":"))

    def _getPodTemplateAnnotations(self, manifest: Dict[str, Any]) -> Dict[str, str] | None:
        """Return pod-level annotations from a workload or Pod manifest."""
        kind = manifest.get("kind")
        if kind == "Pod":
            metadata = manifest.setdefault("metadata", {})
            annotations = metadata.setdefault("annotations", {})
            return annotations if isinstance(annotations, dict) else None
        if kind in {"Deployment", "DaemonSet", "StatefulSet", "Job"}:
            template = manifest.setdefault("spec", {}).setdefault("template", {})
            metadata = template.setdefault("metadata", {})
            annotations = metadata.setdefault("annotations", {})
            return annotations if isinstance(annotations, dict) else None
        return None

    def _parseNetworkSelection(self, item: Dict[str, Any], default_namespace: str) -> tuple[str, str]:
        """Return (nad_name, namespace) from one Multus network selection item."""
        raw_name = str(item.get("name") or "")
        namespace = str(item.get("namespace") or default_namespace)
        if "/" in raw_name:
            namespace, raw_name = raw_name.split("/", 1)
        return raw_name, namespace

    def _firstUsableIp(self, cidr: str) -> str:
        """Return the first usable IPv4 address in a CIDR block."""
        network = ipaddress.ip_network(cidr, strict=False)
        if network.version != 4:
            raise ValueError(f"Kube-OVN manifest generation currently supports IPv4 only: {cidr}")
        hosts = network.hosts()
        try:
            return str(next(hosts))
        except StopIteration:
            return str(network.network_address)

    def _compileNodeK8s(self, node: Node) -> Dict[str, Any]:
        real_nodename = self._getRealNodeName(node)
        if not os.path.exists(real_nodename):
            mkdir(real_nodename)

        cwd = os.getcwd()
        chdir(real_nodename)
        dockerfile = self._computeDockerfile(node)
        with open("Dockerfile", "w", encoding="utf-8") as handle:
            handle.write(dockerfile)
        self._patch_interface_setup_context(Path("Dockerfile"))
        chdir(cwd)

        full_image_name = f"{self.__image_registry_prefix}/{real_nodename}:latest"
        self.__image_entries.append(
            {
                "name": full_image_name,
                "context": f"./{real_nodename}",
            }
        )

        node_name = self._getComposeNodeName(node).replace("_", "-").lower()
        asn = str(node.getAsn())
        role = self._nodeRoleToString(node.getRole())

        annotations = self._getInternetMapNodeMeta(node)
        net_specs = []
        for iface in node.getInterfaces():
            net = iface.getNet()
            net_name = self._getRealNetName(net).replace("_", "-").lower()
            prefix_len = net.getPrefix().prefixlen
            net_specs.append({"name": net_name, "ips": [f"{iface.getAddress()}/{prefix_len}"]})
        if net_specs:
            annotations["k8s.v1.cni.cncf.io/networks"] = json.dumps(net_specs)

        envs = [{"name": "CONTAINER_NAME", "value": node_name}]
        for opt, _scope in node.getScopedRuntimeOptions():
            envs.append({"name": opt.name.upper(), "value": str(opt.value)})

        labels = {
            "app": node_name,
            "seedemu.io/asn": asn,
            "seedemu.io/role": role,
            "seedemu.io/name": node.getName(),
            "seedemu.io/workload": "seedemu",
        }

        return {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
                "name": node_name,
                "namespace": self.__namespace,
                "labels": labels,
            },
            "spec": {
                "replicas": 1,
                "selector": {"matchLabels": {"app": node_name}},
                "template": {
                    "metadata": {"labels": labels, "annotations": annotations},
                    "spec": {
                        "containers": [
                            {
                                "name": "main",
                                "image": full_image_name,
                                "imagePullPolicy": self.__image_pull_policy,
                                "securityContext": {
                                    "privileged": True,
                                    "capabilities": {"add": ["ALL"]},
                                },
                                "command": ["/start.sh"],
                                "env": envs,
                                "volumeMounts": [],
                            }
                        ]
                    },
                },
            },
        }

    def _metaKey(self, key: str) -> str:
        return f"{INTERNET_MAP_META_PREFIX}{key}"

    def _nodeInternetMapRole(self, node: Node) -> str:
        _scope, obj_type, _name = node.getRegistryInfo()
        if obj_type == "hnode":
            return "Host"
        if obj_type == "rnode":
            return "Router"
        if obj_type == "brdnode":
            return "BorderRouter"
        if obj_type == "csnode":
            return "SCION Control Service"
        if obj_type == "snode":
            return "Emulator Service Worker"
        if obj_type == "rs":
            return "Route Server"
        return obj_type

    def _getInternetMapNodeMeta(self, node: Node) -> Dict[str, str]:
        _scope, _obj_type, name = node.getRegistryInfo()
        meta = {
            self._metaKey("asn"): str(node.getAsn()),
            self._metaKey("nodename"): str(name),
            self._metaKey("role"): self._nodeInternetMapRole(node),
        }

        if node.getDisplayName() is not None:
            meta[self._metaKey("displayname")] = str(node.getDisplayName())
        if node.getDescription() is not None:
            meta[self._metaKey("description")] = str(node.getDescription())
        if len(node.getClasses()) > 0:
            meta[self._metaKey("class")] = json.dumps(node.getClasses())

        for key, value in node.getLabel().items():
            meta[self._metaKey(key)] = str(value)

        for index, iface in enumerate(node.getInterfaces()):
            net = iface.getNet()
            meta[self._metaKey(f"net.{index}.name")] = str(net.getName())
            meta[self._metaKey(f"net.{index}.address")] = (
                f"{iface.getAddress()}/{net.getPrefix().prefixlen}"
            )

        return meta

    def _getInternetMapNetMeta(self, net: Network) -> Dict[str, str]:
        scope, _obj_type, name = net.getRegistryInfo()
        meta = {
            self._metaKey("type"): "global" if scope == "ix" else "local",
            self._metaKey("scope"): str(scope),
            self._metaKey("name"): str(name),
            self._metaKey("prefix"): str(net.getPrefix()),
        }

        if net.getDisplayName() is not None:
            meta[self._metaKey("displayname")] = str(net.getDisplayName())
        if net.getDescription() is not None:
            meta[self._metaKey("description")] = str(net.getDescription())

        return meta

    def _patch_interface_setup_context(self, dockerfile_path: Path) -> None:
        dockerfile = dockerfile_path.read_text(encoding="utf-8")
        match = re.search(r"^COPY\s+(\S+)\s+/interface_setup\s*$", dockerfile, re.MULTILINE)
        if not match:
            return

        script_path = dockerfile_path.parent / match.group(1)
        if not script_path.exists():
            return

        script_path.write_text(
            """#!/bin/bash
set -euo pipefail

cidr_to_net() {
    ipcalc -n "$1" | sed -E -n 's/^Network: +([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\/[0-9]{1,2}) +.*/\\1/p'
}

tmpfile="$(mktemp)"
trap 'rm -f "$tmpfile"' EXIT

ip -j addr | jq -cr '.[]' | while read -r iface; do
    ifname="$(jq -cr '.ifname' <<< "$iface")"
    jq -cr '.addr_info[]?' <<< "$iface" | while read -r iaddr; do
        addr="$(jq -cr '"\\(.local)/\\(.prefixlen)"' <<< "$iaddr")"
        net="$(cidr_to_net "$addr")"
        [ -z "$net" ] && continue
        line="$(grep -F "$net" ifinfo.txt || true)"
        [ -z "$line" ] && continue
        new_ifname="$(cut -d: -f1 <<< "$line")"
        latency="$(cut -d: -f3 <<< "$line")"
        bw="$(cut -d: -f4 <<< "$line")"
        loss="$(cut -d: -f5 <<< "$line")"
        [ -z "$new_ifname" ] && continue
        [ "$bw" = 0 ] && bw=1000000000000
        printf '%s|%s|%s|%s|%s\\n' "$ifname" "$new_ifname" "$latency" "$bw" "$loss" >> "$tmpfile"
    done
done

i=0
while IFS='|' read -r ifname new_ifname latency bw loss; do
    [ -z "$ifname" ] && continue
    tmp_ifname="seedtmp${i}"
    if [ "$ifname" != "$new_ifname" ]; then
        ip link set "$ifname" down
        ip link set "$ifname" name "$tmp_ifname"
    else
        tmp_ifname="$ifname"
    fi
    printf '%s|%s|%s|%s|%s\\n' "$tmp_ifname" "$new_ifname" "$latency" "$bw" "$loss" >> "${tmpfile}.stage2"
    i=$((i + 1))
done < "$tmpfile"

while IFS='|' read -r tmp_ifname new_ifname latency bw loss; do
    [ -z "$tmp_ifname" ] && continue
    if [ "$tmp_ifname" != "$new_ifname" ]; then
        ip link set "$tmp_ifname" name "$new_ifname"
    fi
    ip link set "$new_ifname" up
    [ -z "$loss" ] && loss=0
    tc qdisc add dev "$new_ifname" root handle 1:0 tbf rate "${bw}bit" buffer 1000000 limit 1000
    tc qdisc add dev "$new_ifname" parent 1:0 handle 10: netem delay "${latency}ms" loss "${loss}%"
done < "${tmpfile}.stage2"

rm -f "${tmpfile}.stage2"
""",
            encoding="utf-8",
        )

    def _stage_base_image_contexts(self) -> None:
        used_images = sorted(getattr(self, "_used_images", set()))
        if os.path.isdir("base_images"):
            shutil.rmtree("base_images")
        if not used_images:
            return

        for image in used_images:
            digest = md5(image.encode("utf-8")).hexdigest()
            dst_root = os.path.join("base_images", digest)
            os.makedirs(dst_root, exist_ok=True)
            dockerfile = os.path.join(dst_root, "Dockerfile")
            with open(dockerfile, "w", encoding="utf-8") as handle:
                handle.write(f"FROM {image}\n")

NativeKubernetesCompiler = KubernetesCompiler
