#!/bin/bash
chmod +x /interface_setup
/interface_setup
[ ! -d /run/bird ] && mkdir /run/bird
bird -d &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
tail -f /dev/null

