#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.155.0.254 dev net0

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter
sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1
sysctl -w net.ipv4.udp_rmem_min=4000 > /dev/null 2>&1
sysctl -w net.ipv4.udp_wmem_min=4000 > /dev/null 2>&1
sysctl -w net.ipv4.tcp_rmem="4096 131072 6291456" > /dev/null 2>&1
sysctl -w net.ipv4.tcp_wmem="4096 16384 4194304" > /dev/null 2>&1
tail -f /dev/null

