kind: multiHostKvm
clusterName: seedemu-b61-multi-host-kvm

hypervisors:
  - name: amd
    ip: 10.202.236.88
    connection: local
    ssh:
      user: lxl
      key: ~/.ssh/id_ed25519
    routedSubnet:
      cidr: 10.80.1.0/24
      gateway: 10.80.1.1
      networkName: seedemu-amd
      bridgeName: virbr-seed1
      vmIpStart: 10
    vmCount: 3

  - name: idc
    ip: 10.202.191.39
    connection: ssh
    ssh:
      user: seed
      key: ~/.ssh/id_ed25519
    routedSubnet:
      cidr: 10.80.2.0/24
      gateway: 10.80.2.1
      networkName: seedemu-idc
      bridgeName: virbr-seed2
      vmIpStart: 10
    vmCount: 3

vmSsh:
  user: ubuntu
  key: ~/.ssh/id_ed25519

multiHostKvm:
  routingTunnel:
    type: vxlan
    namePrefix: vxkvm
    cidr: 10.255.80.0/24
    vniBase: 4280
    dstPort: 4790
  fabricVxlan:
    vniBase: 6100
    dstPort: 4789

master:
  placement: amd
  name: seed-k3s-master
  vcpus: 16
  memoryMb: 32768
  diskGb: 120

workers:
  namePrefix: seed-k3s-worker
  vcpus: 4
  memoryMb: 16384
  diskGb: 80

fabric:
  type: macvlan-vlan
  mtu: 1400
  vlanTrunks:
    - name: trunk0
      masterInterface: ens3
      vlanStart: 1
      vlanEnd: 4094

cni:
  cniType: macvlan
  localLinkCniType: macvlan
  attachedCniType: macvlan
  defaultMasterInterface: ens3

k3s:
  version: v1.29.15+k3s1

registry:
  port: 5000
