kind: kvm
clusterName: seedemu-b61-kvm

fabric:
  type: macvlan-vlan

cni:
  cniType: macvlan
  localLinkCniType: macvlan
  attachedCniType: macvlan
  defaultMasterInterface: ens2

k3s:
  version: v1.29.15+k3s1

defaults:
  masterName: seedemu-b61-kvm-master
  workerNamePrefix: seedemu-b61-kvm-worker

master:
  vcpus: 12
  memoryMb: 10240
  diskGb: 80

workers:
  count: 3
  vcpus: 6
  memoryMb: 10240
  diskGb: 80

ssh:
  user: ubuntu
  key: ~/.ssh/id_ed25519
