#!/usr/bin/env python3
"""Statically validate B61 KubernetesCompiler output for CI.

Inputs:
- ``output/k8s.yaml``, ``output/networking.yaml``, ``output/images.yaml``, and
  the Docker build contexts generated by ``mini_internet_k8s.py``.
- the three checked-in macvlan deployment YAML files.

Outputs:
- ``kubernetes-compiler-summary.json`` and selected generated contract files
  under ``TEST_RUNNER_ARTIFACT_DIR`` when the standardized test runner sets it.

This script only reads compiler output and renders kustomization metadata. It
does not build images, contact a cluster, create VMs, or modify remote hosts.
Run it from any working directory with Python 3 and PyYAML installed.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml


EXPECTED_NAMESPACE = "seedemu"
EXPECTED_DEPLOYMENTS = 57
EXPECTED_NADS = 29
EXPECTED_CNI_MTU = 1400
EXPECTED_VLAN_START = 100
NETWORKS_ANNOTATION = "k8s.v1.cni.cncf.io/networks"
META_PREFIX = "org.seedsecuritylabs.seedemu.meta."
DNS_SUBDOMAIN = re.compile(r"^[a-z0-9](?:[-a-z0-9.]*[a-z0-9])?$")
HASH_IMAGE = re.compile(r"^[0-9a-f]{32}$")


class ValidationError(RuntimeError):
    """Raised when generated compiler output violates the B61 CI contract."""


def require(condition: bool, message: str) -> None:
    """Raise ValidationError with message when condition is false.

    Args:
        condition: Validation result.
        message: Actionable failure description.
    """
    if not condition:
        raise ValidationError(message)


def findRepoRoot(start: Path) -> Path:
    """Return the repository containing setup.py and seedemu/.

    Args:
        start: File or directory from which to walk upward.
    """
    current = start.resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / "setup.py").is_file() and (candidate / "seedemu").is_dir():
            return candidate
    raise ValidationError(f"cannot find SeedEMU repository root above {start}")


def loadYamlMapping(path: Path) -> dict[str, Any]:
    """Load one YAML mapping from path.

    Args:
        path: YAML file to load.
    """
    require(path.is_file(), f"missing required YAML file: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    require(isinstance(data, dict), f"YAML root must be a mapping: {path}")
    return data


def loadManifestDocuments(path: Path) -> list[dict[str, Any]]:
    """Load all mapping documents from a Kubernetes YAML stream.

    Args:
        path: Multi-document Kubernetes manifest.
    """
    require(path.is_file(), f"missing Kubernetes manifest: {path}")
    with path.open(encoding="utf-8") as handle:
        documents = [doc for doc in yaml.safe_load_all(handle) if doc is not None]
    require(
        all(isinstance(doc, dict) for doc in documents),
        f"manifest contains a non-mapping document: {path}",
    )
    return documents


def resourceKey(document: dict[str, Any]) -> tuple[str, str, str]:
    """Return kind, namespace, and name for one Kubernetes document.

    Args:
        document: Parsed Kubernetes resource.
    """
    metadata = document.get("metadata") if isinstance(document.get("metadata"), dict) else {}
    return (
        str(document.get("kind") or ""),
        str(metadata.get("namespace") or ""),
        str(metadata.get("name") or ""),
    )


def validateResourceNames(documents: list[dict[str, Any]]) -> None:
    """Validate resource identity fields and reject duplicate objects.

    Args:
        documents: Parsed Kubernetes resources.
    """
    seen: set[tuple[str, str, str]] = set()
    for index, document in enumerate(documents, 1):
        api_version = document.get("apiVersion")
        kind, namespace, name = resourceKey(document)
        require(bool(api_version), f"document {index} is missing apiVersion")
        require(bool(kind), f"document {index} is missing kind")
        require(bool(name), f"document {index} is missing metadata.name")
        require(
            len(name) <= 253 and DNS_SUBDOMAIN.fullmatch(name) is not None,
            f"invalid Kubernetes name: {name}",
        )
        key = (kind, namespace, name)
        require(
            key not in seen,
            f"duplicate Kubernetes resource: {kind}/{namespace or '<cluster>'}/{name}",
        )
        seen.add(key)


def parseNads(documents: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Validate macvlan NADs and return their network metadata by name.

    Args:
        documents: Parsed Kubernetes resources.
    """
    nads: dict[str, dict[str, Any]] = {}
    vlan_ids: list[int] = []
    for document in documents:
        if document.get("kind") != "NetworkAttachmentDefinition":
            continue
        require(
            document.get("apiVersion") == "k8s.cni.cncf.io/v1",
            "NAD apiVersion must be k8s.cni.cncf.io/v1",
        )
        metadata = document.get("metadata") if isinstance(document.get("metadata"), dict) else {}
        name = str(metadata.get("name") or "")
        require(
            metadata.get("namespace") == EXPECTED_NAMESPACE,
            f"NAD {name} must use namespace {EXPECTED_NAMESPACE}",
        )
        annotations = (
            metadata.get("annotations") if isinstance(metadata.get("annotations"), dict) else {}
        )
        prefix_text = str(annotations.get(f"{META_PREFIX}prefix") or "")
        vlan_text = str(annotations.get(f"{META_PREFIX}vlan-id") or "")
        base_interface = str(annotations.get(f"{META_PREFIX}vlan-base-interface") or "")
        master_interface = str(annotations.get(f"{META_PREFIX}vlan-master-interface") or "")
        trunk = str(annotations.get(f"{META_PREFIX}vlan-trunk") or "")
        try:
            prefix = ipaddress.ip_network(prefix_text, strict=False)
            vlan_id = int(vlan_text)
        except (ValueError, TypeError) as exc:
            raise ValidationError(f"NAD {name} has invalid prefix or VLAN annotation") from exc
        require(prefix.version == 4, f"NAD {name} must use an IPv4 prefix")
        require(1 <= vlan_id <= 4094, f"NAD {name} VLAN is outside 1..4094: {vlan_id}")
        require(base_interface == "ens2", f"baseline NAD {name} must use compile placeholder ens2")
        require(
            master_interface == f"ens2.{vlan_id}",
            f"NAD {name} master annotation does not match VLAN",
        )
        require(trunk == "trunk0", f"NAD {name} must use trunk0")

        spec = document.get("spec") if isinstance(document.get("spec"), dict) else {}
        raw_config = spec.get("config")
        require(isinstance(raw_config, str), f"NAD {name} spec.config must be a JSON string")
        try:
            config = json.loads(raw_config)
        except json.JSONDecodeError as exc:
            raise ValidationError(f"NAD {name} spec.config is invalid JSON") from exc
        require(isinstance(config, dict), f"NAD {name} spec.config must decode to a mapping")
        require(config.get("cniVersion") == "0.3.1", f"NAD {name} has unexpected cniVersion")
        require(config.get("type") == "macvlan", f"NAD {name} must use macvlan")
        require(
            config.get("master") == master_interface,
            f"NAD {name} config master disagrees with annotation",
        )
        require(config.get("mode") == "bridge", f"NAD {name} macvlan mode must be bridge")
        require(
            config.get("mtu") == EXPECTED_CNI_MTU, f"NAD {name} MTU must be {EXPECTED_CNI_MTU}"
        )
        ipam = config.get("ipam") if isinstance(config.get("ipam"), dict) else {}
        require(ipam.get("type") == "static", f"NAD {name} must use static IPAM")
        require(name not in nads, f"duplicate NAD name: {name}")
        nads[name] = {"prefix": prefix, "vlan": vlan_id, "config": config}
        vlan_ids.append(vlan_id)

    require(len(nads) == EXPECTED_NADS, f"expected {EXPECTED_NADS} NADs, found {len(nads)}")
    expected_vlans = list(range(EXPECTED_VLAN_START, EXPECTED_VLAN_START + EXPECTED_NADS))
    require(
        sorted(vlan_ids) == expected_vlans,
        f"NAD VLAN allocation must be contiguous {expected_vlans[0]}..{expected_vlans[-1]}",
    )
    return nads


def validateDeployments(
    documents: list[dict[str, Any]],
    nads: dict[str, dict[str, Any]],
) -> set[str]:
    """Validate workload structure and return referenced container images.

    Args:
        documents: Parsed Kubernetes resources.
        nads: Validated NAD metadata keyed by name.
    """
    deployments = [document for document in documents if document.get("kind") == "Deployment"]
    require(
        len(deployments) == EXPECTED_DEPLOYMENTS,
        f"expected {EXPECTED_DEPLOYMENTS} Deployments, found {len(deployments)}",
    )
    images: set[str] = set()
    referenced_nads: set[str] = set()
    addresses_by_nad: dict[str, set[str]] = {name: set() for name in nads}

    for deployment in deployments:
        metadata = (
            deployment.get("metadata") if isinstance(deployment.get("metadata"), dict) else {}
        )
        name = str(metadata.get("name") or "")
        require(deployment.get("apiVersion") == "apps/v1", f"Deployment {name} must use apps/v1")
        require(
            metadata.get("namespace") == EXPECTED_NAMESPACE,
            f"Deployment {name} must use namespace {EXPECTED_NAMESPACE}",
        )
        spec = deployment.get("spec") if isinstance(deployment.get("spec"), dict) else {}
        require(spec.get("replicas") == 1, f"Deployment {name} must have one replica")
        selector = spec.get("selector") if isinstance(spec.get("selector"), dict) else {}
        match_labels = (
            selector.get("matchLabels") if isinstance(selector.get("matchLabels"), dict) else {}
        )
        template = spec.get("template") if isinstance(spec.get("template"), dict) else {}
        template_metadata = (
            template.get("metadata") if isinstance(template.get("metadata"), dict) else {}
        )
        template_labels = (
            template_metadata.get("labels")
            if isinstance(template_metadata.get("labels"), dict)
            else {}
        )
        require(bool(match_labels), f"Deployment {name} selector.matchLabels is empty")
        require(
            all(template_labels.get(key) == value for key, value in match_labels.items()),
            f"Deployment {name} selector does not match pod labels",
        )

        pod_spec = template.get("spec") if isinstance(template.get("spec"), dict) else {}
        for forbidden in ("nodeName", "nodeSelector", "affinity", "topologySpreadConstraints"):
            require(
                forbidden not in pod_spec,
                f"Deployment {name} must remain inventory-independent; found {forbidden}",
            )
        containers = (
            pod_spec.get("containers") if isinstance(pod_spec.get("containers"), list) else []
        )
        require(
            len(containers) == 1 and isinstance(containers[0], dict),
            f"Deployment {name} must contain one main container",
        )
        container = containers[0]
        image = str(container.get("image") or "")
        require(bool(image), f"Deployment {name} container image is empty")
        require(
            image not in images, f"container image is reused by multiple B61 Deployments: {image}"
        )
        require(
            container.get("imagePullPolicy") == "Always",
            f"Deployment {name} must use imagePullPolicy Always",
        )
        security = (
            container.get("securityContext")
            if isinstance(container.get("securityContext"), dict)
            else {}
        )
        require(
            security.get("privileged") is True,
            f"Deployment {name} must be privileged for network emulation",
        )
        images.add(image)

        annotations = (
            template_metadata.get("annotations")
            if isinstance(template_metadata.get("annotations"), dict)
            else {}
        )
        raw_networks = annotations.get(NETWORKS_ANNOTATION)
        require(
            isinstance(raw_networks, str),
            f"Deployment {name} is missing the Multus networks annotation",
        )
        try:
            networks = json.loads(raw_networks)
        except json.JSONDecodeError as exc:
            raise ValidationError(f"Deployment {name} Multus annotation is invalid JSON") from exc
        require(
            isinstance(networks, list) and networks,
            f"Deployment {name} Multus network list is empty",
        )
        for selection in networks:
            require(
                isinstance(selection, dict),
                f"Deployment {name} has a non-mapping network selection",
            )
            nad_name = str(selection.get("name") or "")
            require(nad_name in nads, f"Deployment {name} references unknown NAD {nad_name}")
            ips = selection.get("ips") if isinstance(selection.get("ips"), list) else []
            require(bool(ips), f"Deployment {name} network {nad_name} lacks a static address")
            for raw_ip in ips:
                try:
                    interface = ipaddress.ip_interface(str(raw_ip))
                except ValueError as exc:
                    raise ValidationError(
                        f"Deployment {name} has invalid static address {raw_ip}"
                    ) from exc
                require(interface.version == 4, f"Deployment {name} address {raw_ip} must be IPv4")
                require(
                    interface.ip in nads[nad_name]["prefix"],
                    f"Deployment {name} address {raw_ip} is outside NAD {nad_name}",
                )
                address = str(interface.ip)
                require(
                    address not in addresses_by_nad[nad_name],
                    f"duplicate static address on NAD {nad_name}: {address}",
                )
                addresses_by_nad[nad_name].add(address)
            referenced_nads.add(nad_name)

    require(
        referenced_nads == set(nads),
        "every generated NAD must be referenced by at least one Deployment",
    )
    return images


def dockerfileFromImage(dockerfile: Path) -> str:
    """Return the first image from a Dockerfile FROM instruction.

    Args:
        dockerfile: Dockerfile to inspect.
    """
    for raw_line in dockerfile.read_text(encoding="utf-8").splitlines():
        parts = shlex.split(raw_line, comments=True)
        if not parts or parts[0].upper() != "FROM":
            continue
        index = 1
        while index < len(parts) and parts[index].startswith("--"):
            index += 1
        require(index < len(parts), f"Dockerfile FROM has no image: {dockerfile}")
        return parts[index]
    raise ValidationError(f"Dockerfile has no FROM instruction: {dockerfile}")


def validateDockerfileCopies(dockerfile: Path) -> None:
    """Ensure simple compiler-generated COPY sources exist in their context.

    Args:
        dockerfile: Dockerfile whose context is its parent directory.
    """
    for raw_line in dockerfile.read_text(encoding="utf-8").splitlines():
        parts = shlex.split(raw_line, comments=True)
        if not parts or parts[0].upper() != "COPY":
            continue
        values = [part for part in parts[1:] if not part.startswith("--")]
        require(len(values) >= 2, f"invalid COPY instruction in {dockerfile}: {raw_line}")
        for source in values[:-1]:
            require(
                not any(char in source for char in "*?[]"),
                f"unexpected wildcard COPY source in {dockerfile}: {source}",
            )
            source_path = (dockerfile.parent / source).resolve()
            require(
                dockerfile.parent.resolve() in (source_path, *source_path.parents),
                f"COPY source escapes build context: {source}",
            )
            require(source_path.exists(), f"COPY source is missing for {dockerfile}: {source}")


def validateImages(output_dir: Path, deployment_images: set[str]) -> list[dict[str, str]]:
    """Validate images.yaml and all referenced Docker build contexts.

    Args:
        output_dir: Compiler output directory.
        deployment_images: Image references found in Deployments.
    """
    payload = loadYamlMapping(output_dir / "images.yaml")
    raw_images = payload.get("images")
    require(isinstance(raw_images, list), "images.yaml field images must be a list")
    require(
        len(raw_images) == EXPECTED_DEPLOYMENTS,
        f"expected {EXPECTED_DEPLOYMENTS} image entries, found {len(raw_images)}",
    )
    entries: list[dict[str, str]] = []
    image_names: set[str] = set()
    contexts: set[Path] = set()
    referenced_hash_bases: set[str] = set()
    output_root = output_dir.resolve()

    for index, item in enumerate(raw_images):
        require(isinstance(item, dict), f"images.yaml entry {index} must be a mapping")
        name = str(item.get("name") or "")
        context_text = str(item.get("context") or "")
        require(
            name.startswith("seedemu/") and name.endswith(":latest"),
            f"invalid logical image name: {name}",
        )
        require(name not in image_names, f"duplicate images.yaml name: {name}")
        context_path = Path(context_text)
        require(not context_path.is_absolute(), f"image context must be relative: {context_text}")
        resolved_context = (output_dir / context_path).resolve()
        require(
            output_root in (resolved_context, *resolved_context.parents),
            f"image context escapes compiler output: {context_text}",
        )
        require(resolved_context.is_dir(), f"image context directory is missing: {context_text}")
        require(resolved_context not in contexts, f"duplicate image context: {context_text}")
        dockerfile = resolved_context / "Dockerfile"
        require(
            dockerfile.is_file() and dockerfile.stat().st_size > 0,
            f"missing or empty Dockerfile: {dockerfile}",
        )
        validateDockerfileCopies(dockerfile)
        base_image = dockerfileFromImage(dockerfile)
        if HASH_IMAGE.fullmatch(base_image):
            referenced_hash_bases.add(base_image)
        image_names.add(name)
        contexts.add(resolved_context)
        entries.append({"name": name, "context": context_text})

    require(image_names == deployment_images, "Deployment images and images.yaml entries differ")
    base_root = output_dir / "base_images"
    for base_image in referenced_hash_bases:
        dockerfile = base_root / base_image / "Dockerfile"
        require(
            dockerfile.is_file() and dockerfile.stat().st_size > 0,
            f"missing generated base image context: {base_image}",
        )
        require(
            not HASH_IMAGE.fullmatch(dockerfileFromImage(dockerfile)),
            f"base image {base_image} must resolve to an external image",
        )
    return entries


def validateNetworking(output_dir: Path) -> dict[str, Any]:
    """Validate compile-time networking metadata.

    Args:
        output_dir: Compiler output directory.
    """
    networking = loadYamlMapping(output_dir / "networking.yaml")
    require(
        networking.get("compiler") == "Kubernetes", "networking.yaml compiler must be Kubernetes"
    )
    require(networking.get("networkBackend") == "macvlan", "network backend must be macvlan")
    require(networking.get("cniType") == "macvlan", "CNI type must be macvlan")
    require(
        networking.get("cniMasterInterface") == "ens2",
        "no-argument compile parent placeholder must be ens2",
    )
    require(
        networking.get("cniMtu") == EXPECTED_CNI_MTU, f"compile MTU must be {EXPECTED_CNI_MTU}"
    )
    require(networking.get("macvlanVlanMode") is True, "macvlan VLAN mode must be enabled")
    require(
        networking.get("macvlanVlanIdStart") == EXPECTED_VLAN_START,
        f"first VLAN must be {EXPECTED_VLAN_START}",
    )
    require(networking.get("runtimeManifest") == "k8s.yaml", "runtime manifest must be k8s.yaml")
    trunks = networking.get("macvlanVlanTrunks")
    require(
        isinstance(trunks, list) and len(trunks) == 1,
        "baseline compile must contain one VLAN trunk",
    )
    trunk = trunks[0] if isinstance(trunks[0], dict) else {}
    require(
        trunk == {"name": "trunk0", "masterInterface": "ens2", "vlanStart": 100, "vlanEnd": 4094},
        "baseline VLAN trunk metadata changed",
    )
    return networking


def runCommand(args: list[str], *, cwd: Path | None = None) -> str:
    """Run one non-destructive validation helper and return stdout.

    Args:
        args: Command argument vector.
        cwd: Optional working directory.
    """
    result = subprocess.run(
        args,
        cwd=str(cwd) if cwd is not None else None,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "").strip()
        raise ValidationError(
            f"command failed ({result.returncode}): {' '.join(args)}\n{message[-2000:]}"
        )
    return result.stdout


def writeRunningConfig(path: Path, setup_config: Path, output_dir: Path) -> None:
    """Write the minimal running-stage config used for static rendering.

    Args:
        path: Destination YAML path.
        setup_config: Generated or physical configK3s-compatible YAML.
        output_dir: Compiler output directory.
    """
    path.write_text(
        yaml.safe_dump(
            {"setupConfig": str(setup_config.resolve()), "outputDir": str(output_dir.resolve())},
            sort_keys=False,
        ),
        encoding="utf-8",
    )


def effectiveNadConfigs(
    documents: list[dict[str, Any]],
    kustomization: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """Apply generated NAD patches and return effective configs.

    Args:
        documents: Original compiler Kubernetes resources.
        kustomization: Parsed deployment-specific kustomization.yaml.
    """
    configs: dict[str, dict[str, Any]] = {}
    for document in documents:
        if document.get("kind") != "NetworkAttachmentDefinition":
            continue
        metadata = document.get("metadata") if isinstance(document.get("metadata"), dict) else {}
        raw_config = (document.get("spec") or {}).get("config")
        configs[str(metadata.get("name") or "")] = json.loads(str(raw_config))

    patches = kustomization.get("patches") or []
    require(isinstance(patches, list), "kustomization patches must be a list")
    for item in patches:
        require(isinstance(item, dict), "kustomization patch entry must be a mapping")
        target = item.get("target") if isinstance(item.get("target"), dict) else {}
        require(
            target.get("kind") == "NetworkAttachmentDefinition",
            "only NADs may receive CNI patches",
        )
        name = str(target.get("name") or "")
        require(name in configs, f"kustomization patch targets unknown NAD: {name}")
        operations = yaml.safe_load(str(item.get("patch") or ""))
        require(
            isinstance(operations, list) and len(operations) == 1,
            f"NAD {name} patch must contain one operation",
        )
        operation = operations[0] if isinstance(operations[0], dict) else {}
        require(
            operation.get("op") == "replace" and operation.get("path") == "/spec/config",
            f"NAD {name} patch must replace /spec/config",
        )
        value = operation.get("value")
        require(isinstance(value, str), f"NAD {name} replacement config must be JSON text")
        configs[name] = json.loads(value)
    return configs


def validateDeploymentRendering(
    repo_root: Path,
    example_dir: Path,
    output_dir: Path,
    documents: list[dict[str, Any]],
    artifact_dir: Path | None,
) -> dict[str, dict[str, Any]]:
    """Render and validate local, physical, and multi-host deployment modes.

    Args:
        repo_root: SeedEMU repository root.
        example_dir: B61 example directory.
        output_dir: Compiler output directory.
        documents: Original compiler manifest resources.
        artifact_dir: Optional CI artifact directory for rendered snapshots.
    """
    setup_root = repo_root / "seedemu" / "k8sTools" / "resources" / "setup"
    running_stage = (
        repo_root / "seedemu" / "k8sTools" / "resources" / "running" / "manageRunningStage.py"
    )
    local_input = example_dir / "configKvmMacvlan.yaml"
    physical_input = example_dir / "configPhysicalMacvlan.yaml"
    multi_input = example_dir / "configMultiHostKvmMacvlan.yaml"
    results: dict[str, dict[str, Any]] = {}

    with tempfile.TemporaryDirectory(prefix="seedemu-b61-static-") as temp_text:
        temp_dir = Path(temp_text)
        local_setup = temp_dir / "configK3s-local.yaml"
        multi_setup = temp_dir / "configK3s-multi.yaml"
        runCommand(
            [
                sys.executable,
                str(setup_root / "kvm" / "manageKvmConfig.py"),
                str(local_input),
                "write-k3s-config",
                "--output",
                str(local_setup),
            ],
            cwd=repo_root,
        )
        runCommand(
            [
                sys.executable,
                str(setup_root / "multiHostKvm" / "manageMultiHostKvmConfig.py"),
                "--config",
                str(multi_input),
                "write-global-k3s-config",
                "--output",
                str(multi_setup),
            ],
            cwd=repo_root,
        )

        modes = [
            ("local-kvm", local_setup, "ens2", 1400),
            ("physical", physical_input, "br-seedemu", 1400),
            ("multi-host-kvm", multi_setup, "ens3", 1400),
        ]
        for mode, setup_config, expected_parent, expected_mtu in modes:
            running_config = temp_dir / f"running-{mode}.yaml"
            writeRunningConfig(running_config, setup_config, output_dir)
            runCommand(
                [
                    sys.executable,
                    str(running_stage),
                    "--config",
                    str(running_config),
                    "render-kustomization",
                ],
                cwd=repo_root,
            )
            kustomization_path = output_dir / "kustomization.yaml"
            kustomization = loadYamlMapping(kustomization_path)
            resources = kustomization.get("resources")
            require(
                isinstance(resources, list) and "k8s.yaml" in resources,
                f"{mode} kustomization must include k8s.yaml",
            )
            image_rewrites = kustomization.get("images")
            require(
                isinstance(image_rewrites, list) and len(image_rewrites) == EXPECTED_DEPLOYMENTS,
                f"{mode} must rewrite {EXPECTED_DEPLOYMENTS} images",
            )
            effective_configs = effectiveNadConfigs(documents, kustomization)
            require(len(effective_configs) == EXPECTED_NADS, f"{mode} effective NAD count changed")
            for name, config in effective_configs.items():
                master = str(config.get("master") or "")
                require(
                    master.startswith(f"{expected_parent}."),
                    f"{mode} NAD {name} uses unexpected parent {master}",
                )
                require(
                    config.get("mtu") == expected_mtu, f"{mode} NAD {name} uses unexpected MTU"
                )
            patch_count = len(kustomization.get("patches") or [])
            results[mode] = {
                "parent": expected_parent,
                "mtu": expected_mtu,
                "nads": len(effective_configs),
                "patches": patch_count,
                "images": len(image_rewrites),
            }
            if artifact_dir is not None:
                generated_dir = artifact_dir / "generated"
                generated_dir.mkdir(parents=True, exist_ok=True)
                shutil.copy2(kustomization_path, generated_dir / f"kustomization-{mode}.yaml")
    return results


def copyContractArtifacts(output_dir: Path, artifact_dir: Path | None) -> None:
    """Copy small generated contract files into the CI artifact directory.

    Args:
        output_dir: Compiler output directory.
        artifact_dir: Optional CI artifact directory.
    """
    if artifact_dir is None:
        return
    generated_dir = artifact_dir / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    for filename in ("k8s.yaml", "images.yaml", "networking.yaml"):
        shutil.copy2(output_dir / filename, generated_dir / filename)


def writeSummary(artifact_dir: Path | None, summary: dict[str, Any]) -> None:
    """Print validation summary and optionally persist it for CI upload.

    Args:
        artifact_dir: Optional CI artifact directory.
        summary: Serializable validation result.
    """
    text = json.dumps(summary, indent=2, sort_keys=True)
    print(text)
    if artifact_dir is not None:
        artifact_dir.mkdir(parents=True, exist_ok=True)
        (artifact_dir / "kubernetes-compiler-summary.json").write_text(
            text + "\n", encoding="utf-8"
        )


def parseArgs() -> argparse.Namespace:
    """Parse standalone overrides while honoring standardized runner paths."""
    example_dir = Path(__file__).resolve().parent
    runner_example = os.environ.get("TEST_RUNNER_EMULATION_DIR")
    runner_artifacts = os.environ.get("TEST_RUNNER_ARTIFACT_DIR")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=(
            Path(runner_example).resolve() / "output" if runner_example else example_dir / "output"
        ),
        help="KubernetesCompiler output directory to validate.",
    )
    parser.add_argument(
        "--artifact-dir",
        type=Path,
        default=Path(runner_artifacts).resolve() if runner_artifacts else None,
        help="Optional directory for the JSON summary and generated contract files.",
    )
    return parser.parse_args()


def main() -> int:
    """Validate compiler output, write a summary, and return a CI exit code."""
    args = parseArgs()
    example_dir = Path(__file__).resolve().parent
    repo_root = findRepoRoot(example_dir)
    output_dir = args.output_dir.expanduser().resolve()
    artifact_dir = args.artifact_dir.expanduser().resolve() if args.artifact_dir else None
    summary: dict[str, Any] = {
        "status": "failed",
        "output": str(output_dir),
        "checks": {},
    }
    try:
        required_files = [
            output_dir / name for name in ("k8s.yaml", "networking.yaml", "images.yaml")
        ]
        missing = [str(path) for path in required_files if not path.is_file()]
        require(not missing, f"missing compiler outputs: {', '.join(missing)}")
        documents = loadManifestDocuments(output_dir / "k8s.yaml")
        validateResourceNames(documents)
        namespaces = [document for document in documents if document.get("kind") == "Namespace"]
        require(
            len(namespaces) == 1 and resourceKey(namespaces[0])[2] == EXPECTED_NAMESPACE,
            "manifest must contain exactly one seedemu Namespace",
        )
        nads = parseNads(documents)
        deployment_images = validateDeployments(documents, nads)
        image_entries = validateImages(output_dir, deployment_images)
        networking = validateNetworking(output_dir)
        rendering = validateDeploymentRendering(
            repo_root,
            example_dir,
            output_dir,
            documents,
            artifact_dir,
        )
        copyContractArtifacts(output_dir, artifact_dir)
        summary.update(
            {
                "status": "passed",
                "checks": {
                    "documents": len(documents),
                    "deployments": len(deployment_images),
                    "network_attachment_definitions": len(nads),
                    "images": len(image_entries),
                    "namespace": EXPECTED_NAMESPACE,
                    "network_backend": networking["networkBackend"],
                    "cni_mtu": networking["cniMtu"],
                    "vlan_range": [EXPECTED_VLAN_START, EXPECTED_VLAN_START + EXPECTED_NADS - 1],
                    "deployment_rendering": rendering,
                },
            }
        )
    except Exception as exc:
        summary["error"] = str(exc)
        writeSummary(artifact_dir, summary)
        return 1

    writeSummary(artifact_dir, summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
