#!/usr/bin/env python3
# encoding: utf-8

"""
Real Topology (RR) for KubernetesCompiler.

This script migrates the external real-topology dataset (e.g. generated by
~/lxl_topology/autocoder_test/RR_214_example.py) into a clean, reproducible
Kubernetes/K3s multi-node workflow.

Data files are NOT committed to this repository; they are loaded from an
external directory configured by env vars.

Required external files:
  - assignment.pkl
  - real_topology_<size>.txt

Env (data):
  - SEED_REAL_TOPOLOGY_DIR (default: ~/lxl_topology/autocoder_test)
  - SEED_TOPOLOGY_SIZE (default: 214)
  - SEED_TOPOLOGY_FILE (optional, overrides size-based filename)
  - SEED_ASSIGNMENT_FILE (default: ${SEED_REAL_TOPOLOGY_DIR}/assignment.pkl)

Env (K8s compiler, consistent with other examples):
  - SEED_REGISTRY, SEED_NAMESPACE, SEED_CNI_TYPE, SEED_CNI_MASTER_INTERFACE
  - SEED_SCHEDULING_STRATEGY, SEED_NODE_LABELS_JSON, SEED_IMAGE_PULL_POLICY
  - SEED_OUTPUT_DIR

Optional:
  - SEED_ENABLE_INTERNET_MAP=true  (default: false)
"""

from __future__ import annotations

import ast
import json
import os
import pickle
import sys
from ipaddress import IPv4Network
from typing import Dict, List, Tuple, Any

from seedemu.compiler import KubernetesCompiler, SchedulingStrategy
from seedemu.core import Emulator
from seedemu.layers import Base, Ebgp, Ibgp, Ospf, PeerRelationship, Routing


def _parse_node_labels_json(raw: str) -> Dict[str, Dict[str, str]]:
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid SEED_NODE_LABELS_JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("SEED_NODE_LABELS_JSON must be a JSON object")
    normalized: Dict[str, Dict[str, str]] = {}
    for key, value in data.items():
        if not isinstance(value, dict):
            raise ValueError(f"SEED_NODE_LABELS_JSON['{key}'] must be an object of label->value")
        normalized[str(key)] = {str(k): str(v) for k, v in value.items()}
    return normalized


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "y", "on"}


def _get_output_dir(default_dirname: str) -> str:
    configured = os.environ.get("SEED_OUTPUT_DIR")
    if not configured:
        return os.path.join(os.path.dirname(__file__), default_dirname)
    if os.path.isabs(configured):
        return configured
    return os.path.join(os.path.dirname(__file__), configured)


def _require_file(path: str, env_hint: str) -> str:
    expanded = os.path.expanduser(path)
    if not os.path.isfile(expanded):
        raise FileNotFoundError(
            f"Required file not found: {expanded}\n"
            f"Hint: set {env_hint} to a valid path."
        )
    return expanded


def _load_assignment(path: str) -> Dict[str, Dict[str, Any]]:
    with open(path, "rb") as handle:
        data = pickle.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"assignment.pkl must be a dict, got {type(data)}")
    return data


def _load_topology_data(path: str) -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    with open(path, "r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                raise ValueError(f"Invalid topology line (missing ':'): {raw_line!r}")
            key, value = line.split(":", 1)
            data[key.strip()] = ast.literal_eval(value.strip())
    required_keys = {"ixps", "transit_asns", "stub_asns", "ix_ix_transit_edges", "as_as_ix_edges"}
    missing = sorted(required_keys - set(data.keys()))
    if missing:
        raise ValueError(f"Topology file missing keys: {missing}")
    return data


def _ring_links(nodes: List[int]) -> List[Tuple[int, int]]:
    if len(nodes) < 2:
        return []
    if len(nodes) == 2:
        return [(nodes[0], nodes[1])]
    links: List[Tuple[int, int]] = []
    for i in range(len(nodes)):
        a = nodes[i]
        b = nodes[(i + 1) % len(nodes)]
        links.append((a, b))
    return links


def _make_transit_as(
    base: Base,
    *,
    asn: int,
    prefix: str,
    exchanges: List[int],
    node_prefix: Dict[int, str],
) -> None:
    transit_as = base.createAutonomousSystem(asn)
    routers_by_ix: Dict[int, Any] = {}

    for ix in exchanges:
        router = transit_as.createRouter(f"r{ix}")
        router.joinNetwork(f"ix{ix}", str(IPv4Network(node_prefix[ix])[asn]))
        routers_by_ix[ix] = router

    # Mark a single RR per transit AS (first router in a deterministic ordering).
    if exchanges:
        routers_by_ix[exchanges[0]].makeRouteReflector(True)

    # Connect routers via a simple ring over local networks (OSPF + iBGP reachability).
    links = _ring_links(exchanges)
    subnets = list(IPv4Network(prefix).subnets(prefixlen_diff=8))  # /16 -> /24
    subnet_idx = 1
    for a, b in links:
        if subnet_idx >= len(subnets):
            raise RuntimeError(f"AS{asn}: insufficient subnets in {prefix} for {len(links)} internal links")
        net_name = f"net_{a}_{b}"
        transit_as.createNetwork(net_name, str(subnets[subnet_idx]))
        routers_by_ix[a].joinNetwork(net_name)
        routers_by_ix[b].joinNetwork(net_name)
        subnet_idx += 1


def run() -> None:
    topology_dir = os.environ.get("SEED_REAL_TOPOLOGY_DIR", "~/lxl_topology/autocoder_test")
    topology_size_raw = os.environ.get("SEED_TOPOLOGY_SIZE", "214").strip()
    try:
        topology_size = int(topology_size_raw)
    except ValueError as exc:
        raise ValueError(f"Invalid SEED_TOPOLOGY_SIZE: {topology_size_raw}") from exc

    topology_file = os.environ.get("SEED_TOPOLOGY_FILE")
    if not topology_file:
        topology_file = os.path.join(topology_dir, f"real_topology_{topology_size}.txt")
    assignment_file = os.environ.get("SEED_ASSIGNMENT_FILE") or os.path.join(topology_dir, "assignment.pkl")

    topology_file = _require_file(topology_file, "SEED_TOPOLOGY_FILE (or SEED_REAL_TOPOLOGY_DIR/SEED_TOPOLOGY_SIZE)")
    assignment_file = _require_file(assignment_file, "SEED_ASSIGNMENT_FILE (or SEED_REAL_TOPOLOGY_DIR)")

    assignment = _load_assignment(assignment_file)
    topo = _load_topology_data(topology_file)

    node_prefix: Dict[int, str] = {}
    for value in assignment.values():
        if not isinstance(value, dict) or "asn" not in value or "ipv4" not in value:
            raise ValueError("assignment.pkl entries must be dicts with keys: asn, ipv4")
        node_prefix[int(value["asn"])] = str(value["ipv4"])

    emu = Emulator()
    base = Base()
    ebgp = Ebgp()

    # 1) Internet Exchanges (+ route servers)
    for ixp_name in topo["ixps"]:
        if ixp_name not in assignment:
            raise KeyError(f"IXP '{ixp_name}' not found in assignment.pkl")
        ix_id = int(assignment[ixp_name]["asn"])
        prefix = str(assignment[ixp_name]["ipv4"])
        rs_addr = str(IPv4Network(prefix)[ix_id])
        ix = base.createInternetExchange(ix_id, prefix, rsAddress=rs_addr)
        ix.getPeeringLan().setDisplayName(f"IX-{ix_id}")

    # 2) Transit ASes (one router per connected IXP; ring-connected internally; 1 RR per AS)
    transit_ixs: Dict[int, List[int]] = {}
    for transit_asn_key in topo["transit_asns"]:
        if transit_asn_key not in assignment:
            raise KeyError(f"Transit ASN '{transit_asn_key}' not found in assignment.pkl")
        transit_ixs[int(assignment[transit_asn_key]["asn"])] = []

    connected: Dict[int, set[int]] = {asn: set() for asn in transit_ixs.keys()}
    for ix_a, ix_b, t_asn_key, _ in topo["ix_ix_transit_edges"]:
        if t_asn_key not in assignment:
            raise KeyError(f"Transit ASN '{t_asn_key}' (edge) not found in assignment.pkl")
        t_asn = int(assignment[t_asn_key]["asn"])
        if t_asn not in connected:
            continue
        if ix_a not in assignment or ix_b not in assignment:
            raise KeyError(f"IXP '{ix_a}' or '{ix_b}' (edge) not found in assignment.pkl")
        connected[t_asn].add(int(assignment[ix_a]["asn"]))
        connected[t_asn].add(int(assignment[ix_b]["asn"]))

    for transit_key in topo["transit_asns"]:
        asn = int(assignment[transit_key]["asn"])
        prefix = str(assignment[transit_key]["ipv4"])
        exchanges = sorted(connected.get(asn, set()))
        _make_transit_as(base, asn=asn, prefix=prefix, exchanges=exchanges, node_prefix=node_prefix)

    # 3) Optional stub ASes (no hosts; keep node count aligned with dataset)
    # Only create stubs if present in the dataset.
    for stub_key in topo.get("stub_asns", []):
        if stub_key not in assignment:
            raise KeyError(f"Stub ASN '{stub_key}' not found in assignment.pkl")
        # Find the IXP this stub connects to (provider->stub edges with rel=-1).
        ix_for_stub = None
        for provider, customer, ixp_name, rel in topo["as_as_ix_edges"]:
            if str(customer) == str(stub_key) and int(rel) == -1:
                ix_for_stub = ixp_name
                break
        if ix_for_stub is None:
            raise ValueError(f"Stub ASN '{stub_key}' has no provider edge (rel=-1) in as_as_ix_edges")
        if ix_for_stub not in assignment:
            raise KeyError(f"IXP '{ix_for_stub}' (stub attachment) not found in assignment.pkl")

        asn = int(assignment[stub_key]["asn"])
        prefix = str(assignment[stub_key]["ipv4"])
        ix_id = int(assignment[ix_for_stub]["asn"])

        stub_as = base.createAutonomousSystem(asn)
        stub_as.createNetwork("net0", prefix)
        stub_router = stub_as.createRouter(f"r{ix_id}")
        stub_router.joinNetwork("net0")
        stub_router.joinNetwork(f"ix{ix_id}", str(IPv4Network(node_prefix[ix_id])[asn]))

    # 4) eBGP sessions at IXPs (private peerings)
    for provider, customer, ixp_name, rel in topo["as_as_ix_edges"]:
        if provider not in assignment or customer not in assignment or ixp_name not in assignment:
            raise KeyError(f"Edge references unknown key(s): {(provider, customer, ixp_name)}")
        provider_asn = int(assignment[provider]["asn"])
        customer_asn = int(assignment[customer]["asn"])
        ix_id = int(assignment[ixp_name]["asn"])
        rel_int = int(rel)

        if rel_int == -1:
            relationship = PeerRelationship.Provider
        elif rel_int == 0:
            relationship = PeerRelationship.Peer
        else:
            raise ValueError(f"Unsupported relationship value: {rel_int} (only -1 and 0 are supported)")

        ebgp.addPrivatePeerings(ix_id, [provider_asn], [customer_asn], relationship)

    # Layers
    emu.addLayer(base)
    emu.addLayer(Routing())
    emu.addLayer(ebgp)
    emu.addLayer(Ibgp())
    emu.addLayer(Ospf())
    emu.render()

    # Kubernetes compilation
    registry_prefix = os.environ.get("SEED_REGISTRY", "localhost:5001")
    namespace = os.environ.get("SEED_NAMESPACE", "seedemu")
    cni_type = os.environ.get("SEED_CNI_TYPE", "bridge").strip().lower()
    cni_master_interface = os.environ.get("SEED_CNI_MASTER_INTERFACE", "eth0").strip()
    image_pull_policy = os.environ.get("SEED_IMAGE_PULL_POLICY", "Always").strip()
    scheduling_strategy = os.environ.get("SEED_SCHEDULING_STRATEGY", SchedulingStrategy.AUTO).strip().lower()
    node_labels = _parse_node_labels_json(os.environ.get("SEED_NODE_LABELS_JSON", ""))
    enable_internet_map = _env_bool("SEED_ENABLE_INTERNET_MAP", default=False)

    output_dir = _get_output_dir("output_real_topology_rr")

    k8s = KubernetesCompiler(
        registry_prefix=registry_prefix,
        namespace=namespace,
        use_multus=True,
        internetMapEnabled=enable_internet_map,
        scheduling_strategy=scheduling_strategy,
        node_labels=node_labels,
        cni_type=cni_type,
        cni_master_interface=cni_master_interface,
        generate_services=True,
        image_pull_policy=image_pull_policy,
    )

    if enable_internet_map:
        k8s.attachInternetMap()

    emu.compile(k8s, output_dir, override=True)

    expected_nodes = (
        len(topo["ixps"])
        + sum(len(v) for v in connected.values())
        + len(topo.get("stub_asns", []))
    )
    print("=" * 72)
    print("Real Topology (RR) compilation complete.")
    print("=" * 72)
    print(f"Topology file: {topology_file}")
    print(f"Assignment file: {assignment_file}")
    print(f"Expected nodes (routers + route servers): {expected_nodes}")
    print(f"Output directory: {output_dir}")
    print(f"Namespace: {namespace}")
    print(f"Registry prefix: {registry_prefix}")
    print(f"CNI type: {cni_type}")
    print(f"Internet Map enabled: {enable_internet_map}")


if __name__ == "__main__":
    try:
        run()
    except (FileNotFoundError, KeyError, ValueError, RuntimeError) as exc:
        print(f"[k8s_real_topology_rr] ERROR: {exc}", file=sys.stderr)
        print("Hint: set SEED_REAL_TOPOLOGY_DIR/SEED_TOPOLOGY_FILE/SEED_ASSIGNMENT_FILE and re-run.", file=sys.stderr)
        raise SystemExit(2) from exc
